In [5]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print("Data type of each elements in variable list_ is:")
for i in list_:
    print(type(i))
print("\nData type of each elements in variable array_list is:")
for i in array_list:
    print(type(i))

Data type of each elements in variable list_ is:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each elements in variable array_list is:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_,dtype=int)
print("Data type of each elements in variable list_ is:")
for i in list_:
    print(type(i))
print("\nData type of each elements in variable array_list is:")
for i in array_list:
    print(type(i))

Data type of each elements in variable list_ is:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each elements in variable array_list is:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
shape=np.shape(num_array)
size=np.size(num_array)
print(num_array)
print("\nShape of num_array is: ",shape)
print("\nSize of num_array is: ",size)

[[1 2 3]
 [4 5 6]]

Shape of num_array is:  (2, 3)

Size of num_array is:  6


In [24]:
import numpy as np
a=np.zeros((3,3))
shape=np.shape(a)
size=np.size(a)
print(a)
print("\nShape of a is: ",shape)
print("\nSize of a is: ",size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape of a is:  (3, 3)

Size of a is:  9


In [26]:
import numpy as np
a=np.eye(5)
shape=np.shape(a)
size=np.size(a)
print(a)
print("\nShape of a is: ",shape)
print("\nSize of a is: ",size)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Shape of a is:  (5, 5)

Size of a is:  25
